# -*- coding: utf-8 -*-
"""Covid19_EmployModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3pciWdEf939Uvmxx480jdQbc2kPsRSD
"""

import keras
from keras.models import *
from keras.layers import *
from keras.preprocessing import image
import PIL
from google.colab import drive
from keras.models import load_model
import cv2
from numpy import asarray
import numpy as np


class Covid():

  model=None
  img_expand=None

  def __init__(self):
    drive.mount('/content/drive')
    Covid.model=load_model("/content/drive/MyDrive/H5_Folders/Covid19_CNN.h5")

  def PreProcess(self,Path):
     img =cv2.imread(Path,0)
     img=cv2.resize(img, (100, 100)) 
     img=np.array(img).astype(np.uint8)
     img=img/255.0
     Covid.img_expand=np.expand_dims(img,axis=0)
     return Covid.img_expand

  def Predict(self,Image):
    y_pred_img=Covid.model.predict(Covid.img_expand)
    max_value=y_pred_img[0].max()
    if(max_value == y_pred_img[0][0]):
      return "Covid"
    elif(max_value == y_pred_img[0][1]):
      return "Normal"
    else:
      return "Pneumonia"

covid = Covid()
img=covid.PreProcess("/content/sample_data/Normal-2.jpg")
covid.Predict(img)